
EXCEPTION_MAIL_HOST = "smtp.mxhichina.com"
EXCEPTION_MAIL_USER = "xiamingyu@xywy.com"
EXCEPTION_MAIL_PASS = "Hello1234"
EXCEPTION_MAIL_SENDER = 'xiamingyu@xywy.com'
EXCEPTION_MAIL_RECEIVERS = ['1083298593@qq.com', 'xiamingyu@xywy.com']
EXCEPTION_MAIL_CC_RECEIVER = ''.join(['1277338682@qq.com', ])

ADDUSER_MAIL_HOST = EXCEPTION_MAIL_HOST
ADDUSER_MAIL_USER = EXCEPTION_MAIL_USER
ADDUSER_MAIL_PASS = EXCEPTION_MAIL_PASS
ADDUSER_MAIL_SENDER = EXCEPTION_MAIL_SENDER


